[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Society: Investigating the Social Impacts of Intelligent Technologies on Human Behavior"
